import { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'c1', name: 'Keyboard', iconName: 'Keyboard' },
  { id: 'c2', name: 'Mouse', iconName: 'Mouse' },
  { id: 'c3', name: 'Light', iconName: 'Lightbulb' },
  { id: 'c4', name: 'Microphone', iconName: 'Mic' },
  { id: 'c5', name: 'Monitor Arm', iconName: 'Monitor' },
  { id: 'c6', name: 'Headset', iconName: 'Headphones' },
  { id: 'c7', name: 'iEM', iconName: 'Ear' },
];

export const products: Product[] = [
  // Mice
  {
    id: 'm1',
    name: 'ATTACK SHARK X11',
    fullName: 'ATTACK SHARK X11 Wireless Gaming Mouse with Charging Dock',
    tagline: 'ATTACK SHARK X11 Gaming Mouse with Magnetic Charging Dock, PixArt PAW3311 Gaming Sensor, BT/2.4G Wireless/Wired',
    price: 288.74,
    originalPrice: 339.72,
    discountPercent: 15,
    category: 'Mouse',
    image: '/attack-shark-x11-dock.jpg',
    gallery: [
      '/attack-shark-x11-dock.jpg',
      'https://images.unsplash.com/photo-1615663245857-ac1eeb536628?w=800&q=80',
    ],
    badge: 'NEW',
    rating: 5,
    reviewsCount: 731,
    inStock: true,
    description: 'The ATTACK SHARK X11 combines precision esports performance with supreme magnetic charging convenience. Powered by the high-precision PixArt PAW3311 sensor and TTC mechanical encoder, it delivers swift, pinpoint tracking on any surface. Its 63g ultra-lightweight body reduces wrist strain during intense sessions, while the dedicated magnetic RGB dock charges your mouse quickly and acts as a 1000Hz wireless receiver desk hub.',
    features: [
      'Charging Dock',
      '3311 Gaming Sensor',
      'BK3633 Tri-Modes',
      '63g Ultra-Light',
      '20 Million Clicks',
      '65 Hours Battery',
      'TTC Encoder',
      'Driver Software',
      'Ergonomic Design',
      'Wide Applicability',
    ],
    specs: [
      { label: 'Sensor', value: 'PixArt PAW3311 Optical' },
      { label: 'Connectivity', value: '2.4GHz Wireless / Bluetooth 5.2 / USB-C Wired' },
      { label: 'Weight', value: '63g ± 2g Ultra-light' },
      { label: 'Battery Life', value: 'Up to 65 hours' },
      { label: 'Charging', value: 'Magnetic RGB Base + Type-C' },
      { label: 'Switches', value: '20 Million Click Micro-switches' },
      { label: 'Polling Rate', value: '1000Hz (1ms response time)' },
      { label: 'DPI Range', value: 'Up to 22,000 DPI (Driver Software)' },
    ],
  },
  {
    id: 'm2',
    name: 'ATTACK SHARK V6',
    fullName: 'ATTACK SHARK V6 Ergonomic Wireless Gaming Mouse with RGB Charging Dock',
    tagline: 'Ergonomic Right-Handed Contour with Thumb Rest, Magnetic RGB Fast Charging Dock, Tri-Mode BT/2.4G/Wired',
    price: 349,
    originalPrice: 420,
    discountPercent: 17,
    category: 'Mouse',
    image: '/attack-shark-v6.png',
    gallery: [
      '/attack-shark-v6.png',
    ],
    rating: 4.9,
    reviewsCount: 312,
    inStock: true,
    description: 'The ATTACK SHARK V6 combines an aggressive ergonomic right-handed contour with a dedicated magnetic RGB desktop charging base. Sculpted with a comfortable flared thumb rest, crisp tactile side buttons, and a precision optical sensor, it provides effortless palm and claw support during marathon gaming sessions. The magnetic dock features vibrant multi-color RGB underglow and keeps your mouse fully charged and wireless dongle within close range for zero latency.',
    features: [
      'Magnetic RGB Charging Dock',
      'Ergonomic Flared Thumb Rest',
      'PAW3395 Gaming Sensor',
      'Tri-Mode Wireless Connectivity',
      'Huano Blue Shell Pink Dot Switches',
      '80 Hours Battery Life',
      'TTC Silver Wheel Encoder',
      'RGB Underglow Lighting Base',
    ],
    specs: [
      { label: 'Form Factor', value: 'Ergonomic Right-Handed with Thumb Rest' },
      { label: 'Charging Dock', value: 'Magnetic Quick-Contact Dock with RGB LED Base' },
      { label: 'Sensor', value: 'PixArt PAW3395 Optical Sensor' },
      { label: 'Connectivity', value: 'Tri-Mode: 2.4G Wireless / Bluetooth 5.2 / USB-C Wired' },
      { label: 'Switches', value: 'Huano Blue Shell Pink Dot Microswitches' },
      { label: 'Battery Life', value: 'Up to 80 Hours Continuous Gaming' },
      { label: 'Receiver', value: 'Compact 2.4G Wireless USB Dongle with Shark Logo' },
    ],
  },
  {
    id: 'm3',
    name: 'ATTACK SHARK V3 PRO',
    fullName: 'ATTACK SHARK V3 PRO Ultra Gaming Mouse',
    tagline: 'Flagship Lightweight Competitive Esports Wireless Mouse',
    price: 399,
    originalPrice: 450,
    discountPercent: 11,
    category: 'Mouse',
    image: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=800&q=80',
    badge: 'SALE',
    rating: 4.8,
    reviewsCount: 189,
    inStock: true,
    features: [
      'Flagship 3395 Sensor',
      '4K Hz Polling Rate Compatible',
      '55g Featherweight',
      'Nordic 52840 MCU',
      'PTFE Glide Skates',
    ],
  },
  {
    id: 'm4',
    name: 'ATTACK SHARK X11 SE',
    fullName: 'ATTACK SHARK X11 SE Tri-Mode Gaming Mouse',
    tagline: 'Affordable High-Performance Wireless Mouse with Magnetic Base',
    price: 249,
    category: 'Mouse',
    image: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=800&q=80',
    rating: 4.7,
    reviewsCount: 240,
    inStock: true,
    features: [
      'PAW3311 Sensor',
      'Magnetic Charge Dock Compatible',
      'Tri-Mode Connectivity',
      '65g Weight',
    ],
  },
  {
    id: 'm5',
    name: 'ATTACK SHARK G3 PRO',
    fullName: 'ATTACK SHARK G3 PRO Tri-Mode Wireless Mouse',
    tagline: 'Esports Grade PAW3395 Sensor with 8K Polling Option',
    price: 429,
    category: 'Mouse',
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=80',
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
    features: [
      'PAW3395 Sensor',
      'Ultra Low Latency',
      'TTC Gold Encoder',
      'Honeycomb Inner Structure',
    ],
  },
  {
    id: 'm6',
    name: 'ATTACK SHARK R1',
    fullName: 'ATTACK SHARK R1 Ultra-Lightweight Wireless Mouse',
    tagline: 'Ergonomic Claw-Grip Wireless Mouse with PAW3311',
    price: 279,
    category: 'Mouse',
    image: 'https://images.unsplash.com/photo-1605773527852-c546a8584ea3?w=800&q=80',
    rating: 4.8,
    reviewsCount: 420,
    inStock: true,
    features: [
      'PAW3311 Sensor',
      'Ergonomic Right-Hand Shape',
      '59g Ultra-Light',
      '2.4G & Bluetooth',
    ],
  },
  {
    id: 'm7',
    name: 'ATTACK SHARK R5 ULTRA',
    fullName: 'ATTACK SHARK R5 ULTRA Carbon Fiber Wireless 8K PAW3950MAX Gaming Mouse with 8K Coiled Cable',
    tagline: '39g SUPERLIGHT, PixArt PAW3950MAX Gaming Sensor, 8000Hz Wireless Polling Rate, MCU Nordic 52840, DPI up to 42000, BT/2.4G Wireless/Wired',
    price: 499,
    originalPrice: 589,
    discountPercent: 15,
    category: 'Mouse',
    image: '/attack-shark-r5-ultra.jpg',
    gallery: [
      '/attack-shark-r5-ultra.jpg',
    ],
    badge: 'PRO',
    rating: 5.0,
    reviewsCount: 51,
    inStock: true,
    description: 'The ATTACK SHARK R5 ULTRA Carbon Fiber Edition is an ultra-lightweight esports tournament weapon weighing just 39 grams. Engineered with an injection-molded carbon fiber composite skeleton, it features the flagship PixArt PAW3950MAX optical sensor offering up to 42,000 DPI and a high-speed Nordic 52840 MCU providing true 8000Hz wireless polling rate (0.125ms latency). Outfitted with 100 Million Clicks Omron microswitches, an F-Switch E10 premium encoder, dedicated 8K wireless receiver dongle, and custom 8K coiled aviator cable, it delivers unmatched precision, zero latency, and tournament-grade reliability.',
    features: [
      '39g Ultra-Lightweight',
      'Injection Molded Carbon Fiber',
      'PAW3950MAX Gaming Sensor',
      'Nordic 52840 Chip',
      'Wireless 8000Hz Polling Rate',
      'F-Switch E10 Premium Encoder',
      '100 Million Clicks Omron Microswitches',
      'Wired/Wireless/Bluetooth Connection',
      'Ergonomic Design',
      'Web Driver Supported',
      'Dimensions: 119.5mm x 61mm x 36.3mm',
    ],
    specs: [
      { label: 'Weight', value: '39g Ultra-Lightweight' },
      { label: 'Material', value: 'Injection Molded Carbon Fiber Skeleton' },
      { label: 'Sensor', value: 'PixArt PAW3950MAX Flagship Gaming Sensor' },
      { label: 'MCU', value: 'Nordic 52840 High-Speed Chip' },
      { label: 'Polling Rate', value: '8000Hz Wireless & Wired (0.125ms Response)' },
      { label: 'Max DPI', value: 'Up to 42,000 DPI (Web Driver Configurable)' },
      { label: 'Switches', value: 'Omron Microswitches (100 Million Clicks)' },
      { label: 'Encoder', value: 'F-Switch E10 Premium Dust-proof Encoder' },
      { label: 'Connectivity', value: 'Tri-Mode: 2.4G Wireless (8K) / Bluetooth / USB-C Wired' },
      { label: 'Included Cable', value: '8K Coiled Aviator Quick-Disconnect Cable' },
      { label: 'Receiver', value: 'Dedicated 8K Wireless Dongle with RGB Status Indicator' },
      { label: 'Dimensions', value: '119.5mm × 61mm × 36.3mm' },
      { label: 'Software', value: 'Web Driver & On-Board Memory Supported' },
    ],
  },
  {
    id: 'm8',
    name: 'ATTACK SHARK X8 ULTRA',
    fullName: 'ATTACK SHARK X8 ULTRA Carbon Fiber Wireless Mouse',
    tagline: 'Esports Tournament Edition with High Precision Tracking',
    price: 549,
    category: 'Mouse',
    image: 'https://images.unsplash.com/photo-1517420879524-86d64ac2f339?w=800&q=80',
    rating: 4.9,
    reviewsCount: 64,
    inStock: true,
    features: [
      'Carbon Fiber Composite',
      'Nordic MCU',
      'PAW3950 Optical Sensor',
      'Zero Latency Wireless',
    ],
  },

  // Keyboards
  {
    id: 'k1',
    name: 'ATTACK SHARK X68 HE',
    fullName: 'ATTACK SHARK X68 HE Magnetic Hall Effect Gaming Keyboard',
    tagline: 'Rapid Trigger, Adjustable Actuation 0.1mm - 4.0mm, RGB Aluminum Plate',
    price: 599,
    category: 'Keyboard',
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    badge: 'HOT',
    rating: 4.9,
    reviewsCount: 512,
    inStock: true,
    features: [
      'Magnetic Hall Effect Switches',
      'Rapid Trigger (0.1mm accuracy)',
      '68-Key Compact Layout',
      'Per-Key RGB Lighting',
      'Hot-Swappable PCB',
    ],
  },
  {
    id: 'k2',
    name: 'ATTACK SHARK R82 HE',
    fullName: 'ATTACK SHARK R82 HE 75% Hall Effect Mechanical Keyboard',
    tagline: 'Magnetic Switches with Gasket Mount & Aluminum Rotary Knob',
    price: 649,
    category: 'Keyboard',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    rating: 4.8,
    reviewsCount: 180,
    inStock: true,
    features: [
      'Hall Effect Magnetic Switches',
      'Gasket Mount Acoustic Dampening',
      'CNC Metal Volume Knob',
      'Tri-Mode Wireless / Type-C',
    ],
  },
  {
    id: 'k3',
    name: 'ATTACK SHARK X68 MAX',
    fullName: 'ATTACK SHARK X68 MAX Wireless Mechanical Keyboard',
    tagline: 'Gasket-Mounted RGB Gaming Keyboard with PBT Keycaps',
    price: 699,
    originalPrice: 799,
    discountPercent: 12,
    category: 'Keyboard',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    badge: 'SALE',
    rating: 4.9,
    reviewsCount: 304,
    inStock: true,
    features: [
      'Tri-Mode Wireless Connectivity',
      'Factory Lubed Switches',
      'Double-Shot PBT Keycaps',
      'Custom OLED Display Screen',
    ],
  },
  {
    id: 'k4',
    name: 'ZIYOULANG T8',
    fullName: 'ZIYOULANG T8 60% RGB Mechanical Keyboard',
    tagline: 'Compact Esports Gaming Keyboard with Blue/Red Mechanical Switches',
    price: 349,
    category: 'Keyboard',
    image: 'https://images.unsplash.com/photo-1606148386121-50e59c869fb4?w=800&q=80',
    rating: 4.6,
    reviewsCount: 142,
    inStock: true,
    features: [
      '68-Keys Compact Size',
      'Vibrant RGB Backlight Effects',
      'Detachable Type-C Cable',
      'Full Anti-Ghosting N-Key Rollover',
    ],
  },

  // Others
  {
    id: 'o1',
    name: 'MICRO GM7',
    fullName: 'MICRO GM7 USB Condenser Gaming Microphone',
    tagline: 'RGB Studio Condenser Mic with Tap-to-Mute & Gain Dial',
    price: 279,
    category: 'Microphone',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80',
    rating: 4.8,
    reviewsCount: 165,
    inStock: true,
    features: [
      'Cardioid Pickup Pattern',
      'Quick Tap-to-Mute Sensor',
      'Dynamic RGB Lighting',
      'Shock Mount & Pop Filter Included',
    ],
  },
  {
    id: 'o2',
    name: 'NORTH BAYOU F80',
    fullName: 'NORTH BAYOU F80 Gas Spring Monitor Desk Arm',
    tagline: 'Heavy-Duty Ergonomic Monitor Arm for 17"-30" Screens (VESA 75/100)',
    price: 349,
    category: 'Monitor Arm',
    image: 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=800&q=80',
    rating: 4.9,
    reviewsCount: 890,
    inStock: true,
    features: [
      'Gas Spring Fluid Articulation',
      'Supports up to 9kg Monitor Weight',
      '360° Screen Rotation & Tilt',
      'Integrated Cable Management Channel',
    ],
  },
  {
    id: 'o3',
    name: 'MONITOR LIGHT RGB',
    fullName: 'ScreenBar RGB Curved Monitor Light Bar',
    tagline: 'Asymmetric Desk Glare-Free Illumination with Backlit RGB Ambience',
    price: 199,
    category: 'Light',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    rating: 4.7,
    reviewsCount: 215,
    inStock: true,
    features: [
      'Zero Screen Reflection Design',
      'Touch Sensor Dimming & CCT Adjustment',
      'Rear Ambient RGB Backlight',
      'USB Powered from PC or Monitor',
    ],
  },
];
